blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.PostListView.as_view(), name='home'),
    path('<published_date>/<slug>/<str:pk>', views.post_detail, name='post_detail'),
    path('create-post/', views.CreatePostView.as_view(), name='create_post'),
    # path('tag/<slug:tag_slug>', views.Tags.as_view(), name='post_list_by_tag'),
    path('edit-comment/<str:pk>', views.EditCommentView.as_view(), name='edit_comment'),
    path('delete-comment/<str:pk>', views.DeleteCommentView.as_view(), name='delete_comment'),
    path('edit-post/<str:pk>', views.EditPostView.as_view(), name='edit_post'),
    path('delete-post/<str:pk>', views.DeletePostView.as_view(), name='delete_post'),
]

practice/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager, self).get_queryset().filter(status='published')


class DraftManager(models.Manager):
    def get_queryset(self):
        return super(DraftManager, self).get_queryset().filter(status='draft')


class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=220)
    body = RichTextField()
    thumbnail = models.ImageField(upload_to='post_thumbnails/%Y/%m/%d/')
    quote_author = models.CharField(blank=True, max_length=20)
    post_quote = models.CharField(blank=True, max_length=300)
    slug = models.SlugField(max_length=225, unique_for_date='published_date')
    status_choices = ('published', 'published'), ('draft', 'draft')
    status = models.CharField(max_length=10, choices=status_choices, default='draft')
    published_date = models.DateField(default=timezone.now)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    tags = TaggableManager()
    objects = models.Manager()
    published = PublishedManager()
    draft = DraftManager()

    def post_detail_content(self):
        return reverse('blog:post_detail', args=[self.published_date, self.slug, self.id])

    class Meta:
        ordering = ('-published_date',)

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='comments', null=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created_at',)

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)
        widgets = {
            'body': forms.Textarea(attrs={'placeholder': 'Your Message'}),
        }

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.utils.text import slugify
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, UpdateView, CreateView

from .forms import CommentForm
from .models import Post, Comment


class CreatePostView(LoginRequiredMixin, CreateView):
    model = Post
    fields = ('title', 'body', 'thumbnail', 'tags', 'status',)
    template_name = 'blog/post/create_post.html'
    success_url = reverse_lazy('account:post_manager')

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)


class PostListView(ListView):
    model = Post
    object_list = Post.published.all()
    paginate_by = 12
    template_name = 'blog/post/post_list.html'


def post_detail(request, published_date, slug, pk):
    post = get_object_or_404(Post, published_date=published_date, slug=slug, id=pk)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()
            return HttpResponseRedirect(reverse('blog:post_detail', args=(published_date, slug, pk)))
    else:
        comment_form = CommentForm()
    # list of similar posts
    post_tags_id = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_id).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-tags', '-published_date')[:6]

    context = {'post': post, 'comment_form': comment_form, 'new_comment': new_comment, 'comments': comments,
               'similar_posts': similar_posts}
    return render(request, 'blog/post/post_detail.html', context)


class EditPostView(LoginRequiredMixin, UpdateView):
    model = Post
    fields = ('title', 'body', 'thumbnail', 'tags', 'status',)
    template_name = 'blog/edit.html'
    success_url = reverse_lazy('account:dashboard')


class DeletePostView(LoginRequiredMixin, DeleteView):
    model = Post
    template_name = 'blog/delete.html'
    success_url = reverse_lazy('account:post_manager')


# comment views
class EditCommentView(UpdateView):
    model = Comment
    fields = ('body',)
    template_name = 'blog/edit.html'
    success_url = reverse_lazy('blog:home')


class DeleteCommentView(DeleteView, ):
    model = Comment
    template_name = 'blog/delete.html'

    # def get_success_url(self) -> str:
    #     return reverse('blog:post_detail', args=(self.post.published_date, self.post.slug, self.post.id))

blog/templates/blog/post/create_post.html
{% extends "main.html" %}
{% block title %}Creat Post{% endblock %}
{% block footer %}<!---->{% endblock %}
{% block content %}
<form style="padding-top:100px" action="." method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <input action="{% url 'blog:home' %}"type="submit" value='submit'>
</form>
{% endblock %}

blog/templates/blog/post/post_detail.html
{% extends "main.html" %}
{% load static %}
{% block title %}{{post.title}}{% endblock %}ß
{% block content %}

<div id="content" class="s-content s-content--blog">

    <div class="row entry-wrap">
        <div class="column lg-12">

            <article class="entry format-standard">

                <header class="entry__header">

                    <h1  id='isolenu' class="entry__title">{{post.title}}</h1>

                    <div class="entry__meta">

                        <div class="entry__meta-author">
                            <svg width="24" height="24" fill="none" viewBox="0 0 24 24"><circle cx="12" cy="8" r="3.25" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"></circle><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M6.8475 19.25H17.1525C18.2944 19.25 19.174 18.2681 18.6408 17.2584C17.8563 15.7731 16.068 14 12 14C7.93201 14 6.14367 15.7731 5.35924 17.2584C4.82597 18.2681 5.70558 19.25 6.8475 19.25Z"></path></svg>
                            <a href="#">{{post.author}}</a> 
                        </div>
                        <div class="entry__meta-date">
                            <svg width="24" height="24" fill="none" viewBox="0 0 24 24"><circle cx="12" cy="12" r="7.25" stroke="currentColor" stroke-width="1.5"></circle><path stroke="currentColor" stroke-width="1.5" d="M12 8V12L14 14"></path></svg>
                            {{post.published_date }}
                        </div>
                        <div class="entry__meta-cat">
                            <svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19.25 17.25V9.75C19.25 8.64543 18.3546 7.75 17.25 7.75H4.75V17.25C4.75 18.3546 5.64543 19.25 6.75 19.25H17.25C18.3546 19.25 19.25 18.3546 19.25 17.25Z"></path><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M13.5 7.5L12.5685 5.7923C12.2181 5.14977 11.5446 4.75 10.8127 4.75H6.75C5.64543 4.75 4.75 5.64543 4.75 6.75V11"></path>
                            </svg> 
                            <span class="cat-links">
                                {% for tag in post.tags.all %}
                                <a href="#">{{ tag.name }}</a>
                                {% endfor %}
                            </span>
                        </div>

                    </div>
                    
                </header>

                <div class="entry__media">
                    <figure class="featured-image">
                        <img src= "{{post.thumbnail.url}}" sizes="(max-width: 2400px) 100vw, 2400px" alt="post thumbnail">
                    </figure>
                </div>

                <div class="content-primary">
                    <div class="entry__content">
                        <p >{{post.body | safe}}</p>
                        {% if post.post_quote %}
                        <blockquote>
                            <p>{{post.post_quote}}</p>
                            <cite>{{post.quote_author}}</cite>
                        </blockquote>
                        {% endif %}

                        <p class="entry__tags">
                            <strong>Tags:</strong>
                            <span class="entry__tag-list">
                                {% for tag in post.tags.filter %}
                                <a href="">{{ tag.name }}</a>
                                {% endfor %}
                            </span>
                        </p>

                        <div class="entry__author-box">
                            <figure class="entry__author-avatar">
                                <img alt="author-profile-photo" src="{{post.author.profile.profile_picture.url}}"  class="avatar">
                            </figure>
                            <div class="entry__author-info">
                                <h5 class="entry__author-name"><a href="#">{{post.author}}</a></h5>
                                <p>{{post.author.profile.bio}}.</p>
                            </div>
                        </div>

                    </div>

            </article>
            <h3>See Similar Posts</h3>
            {% for post in similar_posts %}
                <a href="{{ post.post_detail_content }}">{{post.title}}</a><hr>
            {% endfor %}

            <div class="comments-wrap">

                <div id="comments">
                    <div class="large-12">
                        <h3>{% with comments.count as total_comments %} {{total_comments}} comment{{total_comments | pluralize}}</h3>{% if total_comments == 0 %} <p>Be the first to comment</p> {% endif %} {% endwith %}
                        <ol class="commentlist">
                            {% for comment in post.comments.all %}
                            <li class="depth-1 comment">
                                <div class="comment__avatar">
                                    <img class="avatar" src="{{comment.author.profile.profile_picture.url}}" alt="" width="50" height="50">
                                </div>
                                <div class="comment__content">
                                    <div class="comment__info">
                                        <div class="comment__author">{{comment.author}}</div>
                                        <div class="comment__meta">
                                            <div class="comment__time">{{comment.created_at }}</div>
                                            {% if comment.author == request.user %}<div class="comment__reply"><a class="comment-reply-link" href="{%  url 'blog:edit_comment' comment.id %}">Edit</a><span>  </span><a class="comment-reply-link" href="{%  url 'blog:delete_comment' comment.id %}">Delete</a></div>{% endif %}
                                        </div>
                                    </div>
                                    <div class="comment__text">
                                    <p>{{comment.body | linebreaks}}</p>
                                    </div>
                                </div>
                            </li>
                            {% endfor %}
                        </ol>
                    </div> 
                </div>

                {% if request.user.is_authenticated %}
                <div class="comment-respond">
                    <div id="respond">
                        <h3>Add Comment</h3>
                        <form method="POST" action="{%  url 'blog:post_detail' post.published_date post.slug post.id %}">{% csrf_token %}
                            <div class="comment-field-tolu">{{comment_form.media}}{{comment_form}}</div>
                            <input class="btn btn--primary btn-wide btn--large u-fullwidth" value="Add Comment" type="submit">
                        </form>
                    </div>
                </div>
                {% else %}<button><a href="{% url 'account:login' %}">Login to comment</a></button>{% endif %}

            </div>

        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/post/post_list.html
{% extends "main.html" %}
{% load static %}
{% block title %}Blog Posts{% endblock %}
{% block content %}

{% if page_obj.number == 1 %}
<div class="hero">
    <div class="hero__slider swiper-container">
        <div class="swiper-wrapper">
            <article class="hero__slide swiper-slide">
                <div class="hero__entry-image" style=""></div>
                <div class="hero__entry-text">
                    <div class="hero__entry-text-inner">
                        <div class="hero__entry-meta">
                            <span class="cat-links">
                                <a href="">Welcome Note</a>
                            </span>
                        </div>
                        <h2 class="hero__entry-title">
                            <p>Cliche? probably not this blog.</p>
                        </h2>
                        <p class="hero__entry-desc">FlatNews is a website you publish your articles and also get the latest news update. Our writers are unique, and you will enjoy every bit of their work. Scroll down and click on a topic of interest.</p>
                        <a class="hero__more-link" href="https://twitter.com/tolu_joel_">MADE BY TOLU JOEL</a>
                    </div>
                </div>
            </article>
        </div>
    </div>
    <a href="#bricks" class="hero__scroll-down smoothscroll"><svg width="24" height="24" fill="none" viewBox="0 0 24 24"><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M10.25 6.75L4.75 12L10.25 17.25"></path><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M19.25 12H5"></path></svg><span>Scroll</span></a>
</div>
{% endif %}

{% include "blog/post_list_view.html"%}
{% endblock %}

blog/templates/blog/post/post_manager.html
{% extends "main.html" %}
{% block title %}Welcome{% endblock %}
{% block footer %}<!---->{% endblock %}
{% block content %}

<h1>Published Posts</h1>
{% for post in published_posts %}
<h3><a href="{{post.post_detail_content}}">{{post}}</a> </h3>
<div class="comment-reply-link">
<a href="{% url 'blog:edit_post' post.id %}">Edit</a><span>    </span><a href="{% url 'blog:delete_post' post.id %}">Delete</a></a><hr>
</div>
{% endfor %}

<h1>Drafts</h1>
{% for post in draft_posts %}
<h3><a href="{{post.post_detail_content}}">{{post}}</a></h3>
<div class="comment-reply-link">
<a href="{% url 'blog:edit_post' post.id %}">Edit</a><span>    </span><a href="{% url 'blog:delete_post' post.id %}">Delete</a></a><hr>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/post/tags_by_id.html
{% extends "main.html"%}
{% block title %}{{tag.name}} posts{% endblock %}
{% block content %}
<div class="tags-header-balance">
<div class="s-pageheader">
    <div class="row">
        <div class="column large-12">
            <h1 class="page-title">
                <span class="page-title__small-type">Category:</span>
                {{post.tag.name.capitalize}}
            </h1>
        </div>
    </div>
</div>
{% include "blog/post_list_view.html"%}
{% endblock %}